version: "3.9"

services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - DB_NAME=vulnerable_bank
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=db
      - DB_PORT=5432
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./static/uploads:/app/static/uploads
    networks:
      - vuln_network
    restart: always

  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=vulnerable_bank
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - vuln_network
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:

networks:
  vuln_network:
    driver: bridge

