name: Scan

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  security:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      # Install Semgrep
      - name: Install Semgrep
        run: pip install semgrep

      # Run Semgrep
      - name: Run Semgrep
        run: semgrep --config="p/ci" --json --output semgrep-report.json


      # Install Snyk
      - name: Install Snyk
        run: npm install -g snyk

      # Authenticate Snyk with Personal API Token
      - name: Authenticate Snyk
        run: snyk auth $SNYK_TOKEN
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      # Run Snyk test
      - name: Run Snyk
        run: snyk test --all-projects --json > snyk-report.json
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      # Upload reports as artifacts
      - name: Upload Security Reports
        uses: actions/upload-artifact@v4
        with:
          name: security-reports
          path: |
            semgrep-report.json
            snyk-report.json

      # Send notification to Slack
      - name: Notify Slack
        if: always()
        run: |
          curl -X POST -H 'Content-type: application/json' \
          --data '{"text":"Security scan finished. Check the reports in GitHub Actions artifacts."}' \
          ${{ secrets.SLACK_WEBHOOK_URL }}
